package vista.vistaUsuario;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import modelo.entidades.Cita;
import modelo.entidades.Medico;
import modelo.entidades.Paciente;
import modelo.entidades.Persona;
import vista.VentanaPrincipal;
import vista.VentanaRegistro;
import vista.credenciales.InicioSesion;
import vista.credenciales.Registro;

public class VistaUser extends javax.swing.JPanel {

    Map<String, String> dataMedico = new HashMap();
    public static Registro panelRegistro1 = new Registro();
    
    Paciente paciente = InicioSesion.paciente;
    Medico medicoEncargado = null;
    Cita nuevaCita;

    public VistaUser() {
        initComponents();
        cargarMedicos();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnApartar = new javax.swing.JButton();
        tituloBienvenida = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        cedula = new javax.swing.JLabel();
        infoCedula = new javax.swing.JLabel();
        medico = new javax.swing.JLabel();
        infoMedico = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        infoNombre = new javax.swing.JLabel();
        cita = new javax.swing.JLabel();
        infoCita = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        controladorMotivo = new javax.swing.JScrollPane();
        textoMotivo = new javax.swing.JTextArea();
        cmbMedico = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(198, 212, 222));
        setMinimumSize(new java.awt.Dimension(750, 500));
        setPreferredSize(new java.awt.Dimension(750, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnApartar.setBackground(new java.awt.Color(128, 209, 236));
        btnApartar.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        btnApartar.setForeground(new java.awt.Color(0, 0, 0));
        btnApartar.setText("Apartar cita");
        btnApartar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnApartar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApartarMouseClicked(evt);
            }
        });
        add(btnApartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 120, 30));

        tituloBienvenida.setBackground(new java.awt.Color(128, 209, 236));
        tituloBienvenida.setFont(new java.awt.Font("Noto Sans", 1, 30)); // NOI18N
        tituloBienvenida.setForeground(new java.awt.Color(0, 0, 0));
        tituloBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloBienvenida.setText("Bienvenido User");
        tituloBienvenida.setOpaque(true);
        add(tituloBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 340, 60));

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.setLayout(new java.awt.GridLayout(4, 2, -50, -65));

        cedula.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        cedula.setForeground(new java.awt.Color(0, 0, 0));
        cedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cedula.setText("Cédula:");
        panelDatos.add(cedula);

        infoCedula.setForeground(new java.awt.Color(0, 0, 0));
        infoCedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoCedula.setText("12131313131331");
        panelDatos.add(infoCedula);

        medico.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        medico.setForeground(new java.awt.Color(0, 0, 0));
        medico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medico.setText("Médico de cabecera:");
        panelDatos.add(medico);

        infoMedico.setForeground(new java.awt.Color(0, 0, 0));
        infoMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoMedico.setText("Sin Medico asignado");
        panelDatos.add(infoMedico);

        nombre.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("Nombre registrado:");
        panelDatos.add(nombre);

        infoNombre.setForeground(new java.awt.Color(0, 0, 0));
        infoNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoNombre.setText("Nombre del usuario");
        panelDatos.add(infoNombre);

        cita.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        cita.setForeground(new java.awt.Color(0, 0, 0));
        cita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cita.setText("Cita registrada:");
        panelDatos.add(cita);

        infoCita.setForeground(new java.awt.Color(0, 0, 0));
        infoCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoCita.setText("No");
        panelDatos.add(infoCita);

        add(panelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 380, 160));

        btnModificar.setBackground(new java.awt.Color(128, 209, 236));
        btnModificar.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 0, 0));
        btnModificar.setText("Modificar datos");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 140, 30));

        textoMotivo.setBackground(new java.awt.Color(255, 255, 255));
        textoMotivo.setColumns(20);
        textoMotivo.setLineWrap(true);
        textoMotivo.setRows(5);
        controladorMotivo.setViewportView(textoMotivo);

        add(controladorMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 250, -1));

        cmbMedico.setBackground(new java.awt.Color(255, 255, 255));
        cmbMedico.setForeground(new java.awt.Color(0, 0, 0));
        cmbMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medico a tratar en la consulta" }));
        add(cmbMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 250, -1));

        btnSalir.setBackground(new java.awt.Color(128, 209, 236));
        btnSalir.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        
        VentanaRegistro registro = new VentanaRegistro(null, true);
        panelRegistro1.titulo.setText("Cambio de datos");
        registro.setTitle("Datos Usuario");

        panelRegistro1.remove(panelRegistro1.sesion);
        panelRegistro1.remove(panelRegistro1.cedula);
        panelRegistro1.remove(panelRegistro1.txtCedula);
        panelRegistro1.remove(panelRegistro1.mensajeError);
        panelRegistro1.remove(panelRegistro1.btnRegistro);

        panelRegistro1.txtNombre1.setText(paciente.getNombres()[0]);
        panelRegistro1.txtNombre2.setText(paciente.getNombres()[1]);
        panelRegistro1.txtApellido1.setText(paciente.getApellidos()[0]);
        panelRegistro1.txtApellido2.setText(paciente.getApellidos()[1]);
        panelRegistro1.txtUsuario.setText(paciente.getUserName());
        panelRegistro1.txtPassword.setText(paciente.getPassword());

        registro.panelDatos.add(panelRegistro1);
        registro.setVisible(true);
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnApartarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApartarMouseClicked

        if (btnApartar.getText().equals("Apartar cita")) {

            if (textoMotivo.getText().isEmpty() || cmbMedico.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Por favor llenar los campos requeridos",
                        "Error", JOptionPane.WARNING_MESSAGE);
            } else {

                medicoEncargado = (Medico) VentanaPrincipal.archivoMedico.
                        buscar(dataMedico.get((String) cmbMedico.getSelectedItem()));

                medicoEncargado.getPacientes().add(paciente);
                if (medicoEncargado.getPacientes().size() == 10) {
                    medicoEncargado.setDisponibilidad(false);
                }

                paciente.setMedico(medicoEncargado);

                String referenciaCita = String.valueOf((int) (Math.random() * 1000 + 1));
                nuevaCita = new Cita(referenciaCita, paciente,
                        paciente.getMedico(), textoMotivo.getText());

                medicoEncargado.getCitas().add(nuevaCita);
                paciente.setCita(nuevaCita);

                textoMotivo.setText("");
                cmbMedico.setSelectedIndex(0);

                VentanaPrincipal.archivoMedico.actualizar(medicoEncargado);
                VentanaPrincipal.archivoCita.agregar(nuevaCita);
                VentanaPrincipal.archivoPaciente.actualizar(paciente);

                btnApartar.setText("Cancelar cita");
                JOptionPane.showMessageDialog(this, "Cita registrada",
                        "Exito", JOptionPane.DEFAULT_OPTION);

                if (textoMotivo.isEnabled()) {
                    textoMotivo.setEnabled(false);
                }
                if (cmbMedico.isEnabled()) {
                    cmbMedico.setEnabled(false);
                }

                infoMedico.setText(medicoEncargado.getNombres()[0] + " "
                        + medicoEncargado.getApellidos()[0]);

                infoCita.setText("Si");
                cargarMedicos();
            }
        } else {
            int eleccion = JOptionPane.showConfirmDialog(null, "¿Seguro desea cancelar la cita",
                    "Cancelar cita?", 0);

            if (eleccion == 0) {

                medicoEncargado = (Medico) VentanaPrincipal.archivoMedico.
                        buscar(paciente.getMedico().getCedula());

                for (Paciente pc : medicoEncargado.getPacientes()) {
                    if (pc.getCedula().equals(paciente.getCedula())) {
                        VentanaPrincipal.archivoPaciente.getPacientes().remove(pc);
                        medicoEncargado.getPacientes().remove(pc);
                        break;
                    }
                }
                medicoEncargado.getCitas().remove(nuevaCita);

                if (!medicoEncargado.getDisponibilidad()) {
                    medicoEncargado.setDisponibilidad(true);
                }

                VentanaPrincipal.archivoMedico.actualizar(medicoEncargado);

                paciente.setMedico(null);
                paciente.setCita(null);
                VentanaPrincipal.archivoPaciente.actualizar(paciente);

                VentanaPrincipal.archivoCita.eliminar(nuevaCita);
                VentanaPrincipal.archivoCita.getCitas().remove(nuevaCita);

                JOptionPane.showMessageDialog(this, "Cita cancelada exitosamente",
                        "Exito", JOptionPane.DEFAULT_OPTION);

                btnApartar.setText("Apartar cita");
                infoMedico.setText("Sin medico asignado");
                infoCita.setText("No");

                cargarMedicos();
                if (!textoMotivo.isEnabled()) {
                    textoMotivo.setEnabled(true);
                }
                if (!cmbMedico.isEnabled()) {
                    cmbMedico.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_btnApartarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked

        if (!textoMotivo.getText().isEmpty()) {
            int eleccion = JOptionPane.showConfirmDialog(this, "¿Seguro desea salir?", "Confirmar salida", 0);
            if (eleccion == 0) {
                this.textoMotivo.setText("");
                this.setVisible(false);
                VentanaPrincipal.panelPrincipal.add(VentanaPrincipal.sesion);
                VentanaPrincipal.sesion.setVisible(true);
            }
        }else{
            this.textoMotivo.setText("");
                this.setVisible(false);
                VentanaPrincipal.panelPrincipal.add(VentanaPrincipal.sesion);
                VentanaPrincipal.sesion.setVisible(true);
        }
    }//GEN-LAST:event_btnSalirMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApartar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel cedula;
    private javax.swing.JLabel cita;
    private javax.swing.JComboBox<String> cmbMedico;
    private javax.swing.JScrollPane controladorMotivo;
    private javax.swing.JLabel infoCedula;
    private javax.swing.JLabel infoCita;
    private javax.swing.JLabel infoMedico;
    public static javax.swing.JLabel infoNombre;
    private javax.swing.JLabel medico;
    private javax.swing.JLabel nombre;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JTextArea textoMotivo;
    public static javax.swing.JLabel tituloBienvenida;
    // End of variables declaration//GEN-END:variables

    public void setContent(Persona persona) {

        paciente = (Paciente) persona;
        nuevaCita = paciente.getCita();

        String nombres[] = paciente.getNombres();
        String apellidos[] = paciente.getApellidos();

        VistaUser.tituloBienvenida.setText("Bienvenido " + nombres[0]);
        this.infoCedula.setText(paciente.getCedula());

        if (paciente.getMedico() != null) {
            String nombreMedico
                    = paciente.getMedico().getNombres()[0] + " "
                    + paciente.getMedico().getApellidos()[0];
            this.infoMedico.setText(nombreMedico);
        }

        VistaUser.infoNombre.setText(nombres[0] + " " + apellidos[0]);

        if (paciente.getCita() != null) {
            this.infoCita.setText("Si");
            textoMotivo.setEnabled(false);
            cmbMedico.setEnabled(false);
            btnApartar.setText("Cancelar cita");
        }
    }

    private void cargarMedicos() {

        if (cmbMedico.getItemCount() != 1) {
            cmbMedico.removeAllItems();
            dataMedico.clear();
            cmbMedico.addItem("Medico a tratar en la consulta");
        }
        for (Medico doctor : VentanaPrincipal.archivoMedico.getMedicos()) {
            String nombres[] = doctor.getNombres();
            String apellidos[] = doctor.getApellidos();

            if (doctor.getDisponibilidad()) {

                String nombreMedico = nombres[0] + " " + nombres[1]
                        + " " + apellidos[0] + " " + apellidos[1];

                cmbMedico.addItem(nombreMedico);
                dataMedico.put(nombreMedico, doctor.getCedula());
            }
        }
    }
}
