package vista;

import javax.swing.JOptionPane;
import modelo.entidades.Medico;
import modelo.entidades.Paciente;
import static vista.admin.VistaAdmin.dtmMedico;
import static vista.admin.VistaAdmin.filaMedicos;
import static vista.admin.VistaAdmin.panelRegistro;
import vista.credenciales.InicioSesion;
import vista.credenciales.Registro;
import vista.vistaUsuario.VistaUser;
import static vista.vistaUsuario.VistaUser.panelRegistro1;

public class VentanaRegistro extends javax.swing.JDialog {

    public VentanaRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        mensajeError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana de datos");
        setBackground(new java.awt.Color(198, 212, 222));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 550));

        panelContenedor.setBackground(new java.awt.Color(198, 212, 222));
        panelContenedor.setMaximumSize(new java.awt.Dimension(500, 600));
        panelContenedor.setMinimumSize(new java.awt.Dimension(500, 600));
        panelContenedor.setPreferredSize(new java.awt.Dimension(500, 600));
        panelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistro.setBackground(new java.awt.Color(128, 209, 236));
        btnRegistro.setFont(new java.awt.Font("Noto Sans", 0, 25)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistro.setText("Registrar");
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroMouseClicked(evt);
            }
        });
        panelContenedor.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 160, 50));

        panelDatos.setBackground(new java.awt.Color(198, 212, 222));
        panelDatos.setMaximumSize(new java.awt.Dimension(500, 370));
        panelContenedor.add(panelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 370));

        mensajeError.setForeground(new java.awt.Color(255, 0, 0));
        mensajeError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelContenedor.add(mensajeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 500, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseClicked

        if (this.getTitle().equals("Datos Usuario")) {
            Paciente paciente = InicioSesion.paciente;

            if (panelRegistro1.txtNombre1.getText().isEmpty()
                    && panelRegistro1.txtApellido1.getText().isEmpty()
                    && panelRegistro1.txtUsuario.getText().isEmpty()
                    && panelRegistro1.txtPassword.getText().isEmpty()) {
                mensajeError.setText("Hay campos vacios por favor llenarlos");

            } else if ((VentanaPrincipal.archivoPaciente.
                    buscarUsuario(panelRegistro1.txtUsuario.getText()) != null
                    || VentanaPrincipal.archivoAdmin.
                            buscarUsuario(panelRegistro1.txtUsuario.getText()) != null)
                    && !panelRegistro1.txtUsuario.getText().equals(paciente.getUserName())) {

                mensajeError.setText("No se permite este nombre de usuario");

            } else {
                String nombres[] = new String[2];
                String apellidos[] = new String[2];

                nombres[0] = panelRegistro1.txtNombre1.getText();
                nombres[1] = panelRegistro1.txtNombre2.getText();
                apellidos[0] = panelRegistro1.txtApellido1.getText();
                apellidos[1] = panelRegistro1.txtApellido2.getText();

                paciente.setNombres(nombres);
                paciente.setApellidos(apellidos);
                paciente.setUserName(panelRegistro1.txtUsuario.getText());
                paciente.setPassword(panelRegistro1.txtPassword.getText());

                VentanaPrincipal.archivoPaciente.actualizar(paciente);
                VistaUser.tituloBienvenida.setText("Bienvenido " + nombres[0]);
                VistaUser.infoNombre.setText(nombres[0] + " " + apellidos[0]);

                mensajeError.setText("");
                JOptionPane.showMessageDialog(this, "Modificacion con exito",
                        "Exito", JOptionPane.DEFAULT_OPTION);

                this.dispose();
            }

        } else {

            if (panelRegistro.txtCedula.getText().isEmpty()
                    || panelRegistro.txtNombre1.getText().isEmpty()
                    || panelRegistro.txtApellido1.getText().isEmpty()) {

                mensajeError.setText("Hay campos vacios por favor llenarlos");

            } else if (VentanaPrincipal.archivoMedico.buscar(panelRegistro.txtCedula.getText()) != null
                    || VentanaPrincipal.archivoPaciente.buscar(panelRegistro.txtCedula.getText()) != null) {
                mensajeError.setText("Ya hay una persona con esa cedula registrada");
            } else {
                String nombres[] = new String[2];
                String apellidos[] = new String[2];

                nombres[0] = panelRegistro.txtNombre1.getText();
                nombres[1] = panelRegistro.txtNombre2.getText();

                apellidos[0] = panelRegistro.txtApellido1.getText();
                apellidos[1] = panelRegistro.txtApellido2.getText();

                Medico medico = new Medico();
                medico.setCedula(panelRegistro.txtCedula.getText());
                medico.setNombres(nombres);
                medico.setApellidos(apellidos);

                VentanaPrincipal.archivoMedico.agregar(medico);
                VentanaPrincipal.archivoMedico.getMedicos().add(medico);

                filaMedicos[0] = medico.getCedula();
                
                //Cargue de nombre dependiendo los campos llenos
                if (nombres[1].isEmpty() && apellidos[1].isEmpty()) {
                    filaMedicos[1] = nombres[0] + " " + apellidos[0];

                } else if (nombres[1].isEmpty()) {
                    filaMedicos[1] = nombres[0] + " " + apellidos[0] + " " + apellidos[1];

                } else if (apellidos[1].isEmpty()) {
                    filaMedicos[1] = nombres[0] + " " + nombres[1] + " " + apellidos[0];

                } else {
                    filaMedicos[1] = nombres[0] + " " + nombres[1] + " " + apellidos[0] + " " + apellidos[1];
                }

                filaMedicos[2] = "Si";
                filaMedicos[3] = 0;

                dtmMedico.addRow(filaMedicos);

                panelRegistro.txtCedula.setText("");
                panelRegistro.txtNombre1.setText("");
                panelRegistro.txtNombre2.setText("");
                panelRegistro.txtApellido1.setText("");
                panelRegistro.txtApellido2.setText("");

                mensajeError.setText("");
                JOptionPane.showMessageDialog(this, "Registro exitoso", "Exito",
                        JOptionPane.DEFAULT_OPTION);
            }
        }
    }//GEN-LAST:event_btnRegistroMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel mensajeError;
    private javax.swing.JPanel panelContenedor;
    public javax.swing.JPanel panelDatos;
    // End of variables declaration//GEN-END:variables
}
