/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import modelo.archivos.ArchivoAdmin;
import modelo.archivos.ArchivoCita;
import modelo.archivos.ArchivoMedico;
import modelo.archivos.ArchivoPaciente;
import vista.credenciales.InicioSesion;
import vista.credenciales.Registro;

public class VentanaPrincipal extends javax.swing.JFrame {

    public static InicioSesion sesion;
    public static Registro registro;

    public static ArchivoCita archivoCita = new ArchivoCita();
    public static ArchivoMedico archivoMedico = new ArchivoMedico();
    public static ArchivoPaciente archivoPaciente = new ArchivoPaciente();
    public static ArchivoAdmin archivoAdmin = new ArchivoAdmin();

    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        datosSistema();
        VentanaPrincipal.sesion = new InicioSesion();
        VentanaPrincipal.registro = new Registro();
        VentanaPrincipal.panelPrincipal.add(sesion);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MediCenter");
        setBackground(new java.awt.Color(198, 212, 222));
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(870, 560));
        setName("ventanaPrincipal"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(870, 560));

        panelPrincipal.setBackground(new java.awt.Color(198, 212, 222));
        panelPrincipal.setMinimumSize(new java.awt.Dimension(870, 560));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(870, 560));
        panelPrincipal.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void datosSistema() {
        VentanaPrincipal.archivoCita.getCitas().clear();
        VentanaPrincipal.archivoPaciente.getPacientes().clear();
        VentanaPrincipal.archivoMedico.getMedicos().clear();

        VentanaPrincipal.archivoCita.cargarCitas();
        VentanaPrincipal.archivoPaciente.cargarPacientes();
        VentanaPrincipal.archivoMedico.cargarMedicos();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("vista/imagenes/logo.png"));

        return retValue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
