/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.credenciales;

import javax.swing.ImageIcon;
import modelo.entidades.Paciente;
import vista.VentanaPrincipal;
import vista.admin.VistaAdmin;
import vista.vistaUsuario.VistaUser;

public class InicioSesion extends javax.swing.JPanel {

    public static Paciente paciente;

    private final ImageIcon imagen1 = new ImageIcon(
            getClass().getResource("/vista/imagenes/showImage.png"));
    private final ImageIcon imagen2 = new ImageIcon(
            getClass().getResource("/vista/imagenes/hideImage.png"));

    private VistaUser vistaUser;
    private VistaAdmin vistaAdmin;

    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        usuario = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        show = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        cuenta = new javax.swing.JLabel();
        mensajeError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(198, 212, 222));
        setMinimumSize(new java.awt.Dimension(870, 560));
        setPreferredSize(new java.awt.Dimension(870, 560));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Noto Sans", 1, 50)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Iniciar sesión");
        titulo.setName("titulo"); // NOI18N
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 90));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 160, 30));

        usuario.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 0, 0));
        usuario.setText("Usuario");
        add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        password.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setText("Contraseña");
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/showImage.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 50, 30));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 110, 30));

        btnIngresar.setBackground(new java.awt.Color(128, 209, 236));
        btnIngresar.setFont(new java.awt.Font("Noto Sans", 0, 25)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });
        add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 160, 50));

        cuenta.setForeground(new java.awt.Color(0, 6, 148));
        cuenta.setText("Crear cuenta");
        cuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuentaMouseClicked(evt);
            }
        });
        add(cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        mensajeError.setForeground(new java.awt.Color(255, 0, 0));
        mensajeError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(mensajeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 320, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void cuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuentaMouseClicked
        this.setVisible(false);
        VentanaPrincipal.panelPrincipal.add(VentanaPrincipal.registro);
        VentanaPrincipal.registro.setVisible(true);

        txtUsuario.setText("");
        txtPassword.setText("");
        mensajeError.setText("");
    }//GEN-LAST:event_cuentaMouseClicked

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked

        boolean entradaPaciente = VentanaPrincipal.archivoPaciente.verificarEntrada(txtUsuario.getText(),
                txtPassword.getText());
        boolean entradaAdmin = VentanaPrincipal.archivoAdmin.verificarEntrada(txtUsuario.getText(),
                txtPassword.getText());

        if (txtUsuario.getText().isEmpty() || txtPassword.getText().isEmpty()) {
            mensajeError.setText("Campos vacíos por favor llenarlos");

        } else if (!entradaPaciente && !entradaAdmin) {

            mensajeError.setText("Usuario o contraseña incorrecta");
        } else {
            VentanaPrincipal.datosSistema();
            if (entradaPaciente) {
                paciente = (Paciente) VentanaPrincipal.archivoPaciente.buscarUsuario(txtUsuario.getText());
                vistaUser = new VistaUser();
                vistaUser.setContent(paciente);
                this.setVisible(false);
                VentanaPrincipal.panelPrincipal.add(vistaUser);
                vistaUser.setVisible(true);
            } else {
                vistaAdmin = new VistaAdmin();
                this.setVisible(false);
                VentanaPrincipal.panelPrincipal.add(vistaAdmin);
                vistaAdmin.setVisible(true);
            }
            mensajeError.setText("");
            txtUsuario.setText("");
            txtPassword.setText("");
        }
    }//GEN-LAST:event_btnIngresarMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked

        if (txtPassword.getEchoChar() == (char) 0) {
            txtPassword.setEchoChar('\u2022');
            show.setIcon(imagen1);
        } else {
            txtPassword.setEchoChar((char) 0);
            show.setIcon(imagen2);
        }

    }//GEN-LAST:event_showMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel cuenta;
    private javax.swing.JLabel mensajeError;
    private javax.swing.JLabel password;
    private javax.swing.JButton show;
    private javax.swing.JLabel titulo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
